# Generated by Django 5.0.6 on 2024-06-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
